// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import SafariServices;
@import LocalAuthentication;
@import UIKit;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@protocol CopperNetworkAPIDelegate;
@protocol CopperNetworkAPIDataSource;

SWIFT_PROTOCOL("_TtP9CopperKit6C29API_")
@protocol C29API
@property (nonatomic, strong) id <CopperNetworkAPIDelegate> _Nullable delegate;
@property (nonatomic, strong) id <CopperNetworkAPIDataSource> _Nullable dataSource;
@property (nonatomic, copy) NSString * _Nonnull URL;
@end

@class NSURL;

SWIFT_CLASS("_TtC9CopperKit14C29Application")
@interface C29Application : NSObject
+ (C29Application * _Nonnull)sharedInstance;
@property (nonatomic, copy) NSString * _Nonnull baseURL;
@property (nonatomic) BOOL debug;
- (void)configureForApplication:(NSString * _Nonnull)applicationId;
- (void)closeSession;
- (BOOL)openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication;
@end


@interface C29Application (SWIFT_EXTENSION(CopperKit))
@end


@interface C29Application (SWIFT_EXTENSION(CopperKit))
@end

@protocol CopperRecord;

SWIFT_PROTOCOL("_TtP9CopperKit35C29CopperworksApplicationDataSource_")
@protocol C29CopperworksApplicationDataSource
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSArray<id <CopperRecord>> * _Nonnull records;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nullable logoUri;
@property (nonatomic, readonly, copy) NSString * _Nullable url;
@property (nonatomic, readonly, copy) NSString * _Nullable redirectUri;
@end

@class UIColor;
@class NSCoder;
@class NSDictionary;

SWIFT_CLASS("_TtC9CopperKit25C29CopperworksApplication")
@interface C29CopperworksApplication : NSObject <C29CopperworksApplicationDataSource, NSCoding>
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSArray<id <CopperRecord>> * _Nonnull records;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nullable logoUri;
@property (nonatomic, strong) UIColor * _Nullable color;
@property (nonatomic, copy) NSString * _Nullable url;
@property (nonatomic, copy) NSString * _Nullable redirectUri;
- (nonnull instancetype)initWithApplicationId:(NSString * _Nonnull)applicationId name:(NSString * _Nonnull)name records:(NSArray<id <CopperRecord>> * _Nonnull)records OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
+ (C29CopperworksApplication * _Nullable)fromDictionary:(NSDictionary * _Nonnull)dataDict;
+ (NSArray<C29CopperworksApplication *> * _Nullable)getApplicationsFromDictionary:(NSArray<NSDictionary *> * _Nonnull)dataDict;
@end


@interface C29CopperworksApplication (SWIFT_EXTENSION(CopperKit))
@end

@protocol C29SessionDataSource;

SWIFT_CLASS("_TtC9CopperKit30C29CopperworksApplicationCache")
@interface C29CopperworksApplicationCache : NSObject <NSCoding>
+ (NSString * _Nonnull)C29CopperworksApplicationCacheRefreshNotification;
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
@property (nonatomic, strong) id <C29SessionDataSource> _Nullable session;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (NSArray<id <C29CopperworksApplicationDataSource>> * _Nonnull)getApplications;
- (id <C29CopperworksApplicationDataSource> _Nullable)getApplication:(NSString * _Nonnull)applicationId;
- (void)push:(C29CopperworksApplication * _Nonnull)application;
- (void)remove:(id <C29CopperworksApplicationDataSource> _Nonnull)application;
- (void)update:(C29CopperworksApplication * _Nonnull)replace add:(C29CopperworksApplication * _Nonnull)add;
- (void)setApplications:(NSArray<C29CopperworksApplication *> * _Nonnull)applications;
- (void)removeAll;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface C29CopperworksApplicationCache (SWIFT_EXTENSION(CopperKit))
@end


@interface C29CopperworksApplicationCache (SWIFT_EXTENSION(CopperKit))
- (void)set:(C29CopperworksApplicationCache * _Nonnull)cache;
@end


@protocol CopperAvatar;
@protocol CopperName;
@protocol CopperAddress;
@protocol CopperEmail;
@protocol CopperPhone;
@protocol CopperUsername;
@protocol CopperDate;
@protocol CopperSignature;
enum C29Scope : NSInteger;

SWIFT_PROTOCOL("_TtP9CopperKit21C29IdentityDataSource_")
@protocol C29IdentityDataSource
@property (nonatomic, strong) id <CopperAvatar> _Nullable avatar;
@property (nonatomic, strong) id <CopperName> _Nullable name;
@property (nonatomic, strong) id <CopperAddress> _Nullable address;
@property (nonatomic, strong) id <CopperEmail> _Nullable email;
@property (nonatomic, strong) id <CopperPhone> _Nullable phone;
@property (nonatomic, strong) id <CopperUsername> _Nullable username;
@property (nonatomic, strong) id <CopperDate> _Nullable birthday;
@property (nonatomic, strong) id <CopperSignature> _Nullable signature;
- (id <CopperRecord> _Nullable)getDefaultOrBlank:(enum C29Scope)scope;
- (void)addOrUpdateRecord:(id <CopperRecord> _Nonnull)record;
- (void)removeRecord:(id <CopperRecord> _Nonnull)record;
- (void)sync:(NSArray<id <CopperRecord>> * _Nonnull)record;
- (void)save:(BOOL)forceUpload callback:(void (^ _Nonnull)(BOOL))callback;
- (void)reload;
@end

@class UIImage;

SWIFT_CLASS("_TtC9CopperKit13C29ImageCache")
@interface C29ImageCache : NSObject <NSCoding>
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
@property (nonatomic, strong) id <C29SessionDataSource> _Nullable session;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (void)getImage:(NSString * _Nonnull)url cacheOnDownload:(BOOL)cacheOnDownload callback:(void (^ _Nonnull)(UIImage * _Nullable))callback;
- (void)update:(UIImage * _Nullable)image forUrl:(NSString * _Nonnull)forUrl;
- (void)remove:(NSString * _Nonnull)url;
- (void)removeAll;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface C29ImageCache (SWIFT_EXTENSION(CopperKit))
@end


@interface C29ImageCache (SWIFT_EXTENSION(CopperKit))
- (void)set:(C29ImageCache * _Nonnull)cache;
@end

@class NSDate;
@class CopperRecordObject;

SWIFT_CLASS("_TtC9CopperKit14C29RecordCache")
@interface C29RecordCache : NSObject <NSCoding>
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
@property (nonatomic, strong) NSDate * _Nullable lastServerSyncTimestamp;
@property (nonatomic, strong) id <C29SessionDataSource> _Nullable session;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (id <CopperRecord> _Nullable)getRecord:(enum C29Scope)scope includeDeleted:(BOOL)includeDeleted;
- (NSArray<id <CopperRecord>> * _Nonnull)getAllRecords:(BOOL)includeDeleted;
- (void)add:(id <CopperRecord> _Nonnull)record;
- (void)remove:(enum C29Scope)scope;
- (NSString * _Nonnull)getNextRecordId;
- (void)removeAll;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (void)removeAllInvalid;
- (void)saveToAPI:(id <C29SessionDataSource> _Nonnull)session records:(NSArray<CopperRecordObject *> * _Nonnull)records forceUpload:(BOOL)forceUpload callback:(void (^ _Null_unspecified)(BOOL, NSArray<CopperRecordObject *> * _Nonnull))callback;
- (void)deleteFromAPI:(id <C29SessionDataSource> _Nonnull)session records:(NSArray<CopperRecordObject *> * _Nonnull)records forceDelete:(BOOL)forceDelete callback:(void (^ _Null_unspecified)(BOOL, NSArray<CopperRecordObject *> * _Nonnull))callback;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface C29RecordCache (SWIFT_EXTENSION(CopperKit))
- (void)set:(C29RecordCache * _Nonnull)cache;
@end


@interface C29RecordCache (SWIFT_EXTENSION(CopperKit))
- (void)save:(id <C29SessionDataSource> _Nonnull)session callback:(void (^ _Nonnull)(BOOL))callback;
@end

@class C29RequestPlatform;

SWIFT_PROTOCOL("_TtP9CopperKit20C29RequestDataSource_")
@protocol C29RequestDataSource
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull applicationId;
@property (nonatomic, readonly) BOOL expired;
@property (nonatomic, readonly, strong) NSDate * _Nonnull timestamp;
@property (nonatomic, readonly, copy) NSString * _Nullable scopesString;
@property (nonatomic, readonly, strong) C29RequestPlatform * _Nullable platform;
@property (nonatomic, readonly) NSInteger status;
@property (nonatomic, readonly) BOOL responded;
@property (nonatomic, readonly) BOOL complete;
@property (nonatomic, copy) NSArray<id <CopperRecord>> * _Nonnull records;
@end

enum C29RequestStatus : NSInteger;

SWIFT_CLASS("_TtC9CopperKit10C29Request")
@interface C29Request : NSObject <C29RequestDataSource, NSCoding>
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, strong) NSDate * _Nonnull timestamp;
@property (nonatomic, copy) NSString * _Nonnull applicationId;
@property (nonatomic, copy) NSString * _Nullable scopesString;
@property (nonatomic, strong) C29RequestPlatform * _Nullable platform;
@property (nonatomic) NSInteger status;
@property (nonatomic, copy) NSArray<id <CopperRecord>> * _Nonnull records;
@property (nonatomic, readonly) BOOL responded;
@property (nonatomic, readonly) BOOL expired;
@property (nonatomic, readonly) BOOL complete;
- (C29CopperworksApplication * _Nullable)getApplication:(id <C29SessionDataSource> _Nonnull)session;
- (nonnull instancetype)initWithRequestData:(id <C29RequestDataSource> _Nonnull)requestData;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
+ (void)getRequest:(id <C29SessionDataSource> _Nonnull)session requestId:(NSString * _Nonnull)requestId callback:(void (^ _Nonnull)(id <C29RequestDataSource> _Nullable))callback;
- (void)sendResponse:(id <C29SessionDataSource> _Nonnull)session status:(enum C29RequestStatus)status callback:(void (^ _Nonnull)(BOOL, BOOL))callback;
- (void)setAck:(id <C29SessionDataSource> _Nonnull)session;
@end


@interface C29Request (SWIFT_EXTENSION(CopperKit))
@end


@interface C29Request (SWIFT_EXTENSION(CopperKit))
@end



SWIFT_CLASS("_TtC9CopperKit15C29RequestGrant")
@interface C29RequestGrant : NSObject
+ (C29RequestGrant * _Nullable)fromDictionary:(NSDictionary * _Nonnull)dataDict;
@end


SWIFT_CLASS("_TtC9CopperKit18C29RequestPlatform")
@interface C29RequestPlatform : NSObject <NSCoding>
- (nonnull instancetype)initWithType:(NSString * _Nonnull)type version:(NSString * _Nonnull)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
@end


SWIFT_CLASS("_TtC9CopperKit15C29RequestStack")
@interface C29RequestStack : NSObject <NSCoding>
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, strong) id <C29SessionDataSource> _Nullable session;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (void)push:(id <C29RequestDataSource> _Nonnull)request display:(BOOL)display;
- (void)attemptPop;
- (C29Request * _Nullable)pop;
- (void)requestWasDismissed:(NSString * _Nonnull)requestId;
- (void)addResponded:(NSString * _Nonnull)requestId;
- (BOOL)isResponded:(NSString * _Nonnull)requestId;
- (id <C29RequestDataSource> _Nullable)getRequest:(NSString * _Nonnull)requestId;
- (BOOL)contains:(NSString * _Nonnull)requestId;
- (void)removeAll;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface C29RequestStack (SWIFT_EXTENSION(CopperKit))
@end


@interface C29RequestStack (SWIFT_EXTENSION(CopperKit))
- (void)set:(C29RequestStack * _Nonnull)stack;
@end

typedef SWIFT_ENUM(NSInteger, C29RequestStatus) {
  C29RequestStatusApproved = 1,
  C29RequestStatusDismissed = 0,
  C29RequestStatusReported = -1,
  C29RequestStatusUnanswered = -29,
};

typedef SWIFT_ENUM(NSInteger, C29Scope) {
  C29ScopeNull = -1,
  C29ScopeName = 1000,
  C29ScopeAvatar = 1001,
  C29ScopePhone = 1002,
  C29ScopeEmail = 1003,
  C29ScopeUsername = 1004,
  C29ScopeAddress = 1005,
  C29ScopeBirthday = 1006,
  C29ScopeSignature = 1007,
  C29ScopeContactsFavorites = 3001,
};

@class NSData;
@class NSError;
@class C29VerificationCode;

SWIFT_PROTOCOL("_TtP9CopperKit21C29SessionCoordinator_")
@protocol C29SessionCoordinator
- (void)saveUserRecords:(NSArray<CopperRecordObject *> * _Nonnull)records callback:(void (^ _Nonnull)(BOOL))callback;
- (void)deleteUserRecords:(NSArray<CopperRecordObject *> * _Nonnull)records callback:(void (^ _Nonnull)(BOOL))callback;
- (void)getRequest:(NSString * _Nonnull)requestId callback:(void (^ _Nonnull)(C29Request * _Nullable))callback;
- (void)createByteFromFile:(NSString * _Nonnull)fileId data:(NSData * _Nonnull)data callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)setRequestGrant:(C29Request * _Nonnull)request status:(enum C29RequestStatus)status records:(NSArray<id <CopperRecord>> * _Nonnull)records forceRecordUpload:(BOOL)forceRecordUpload callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)setRequestAck:(C29Request * _Nonnull)request;
- (void)deleteUserApplication:(id <C29CopperworksApplicationDataSource> _Nonnull)application callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getURLforCode:(NSString * _Nonnull)code callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)postUserVerification:(C29VerificationCode * _Nonnull)verificationCode digits:(NSString * _Nonnull)digits callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
@end

@class C29User;

SWIFT_PROTOCOL("_TtP9CopperKit20C29SessionDataSource_")
@protocol C29SessionDataSource
@property (nonatomic, readonly, copy) NSString * _Nullable userId;
@property (nonatomic, readonly, strong) C29RequestStack * _Nonnull requestStack;
@property (nonatomic, readonly, strong) C29CopperworksApplicationCache * _Nonnull applicationCache;
@property (nonatomic, readonly, strong) C29RecordCache * _Nonnull recordCache;
@property (nonatomic, readonly, strong) C29ImageCache * _Nonnull imageCache;
@property (nonatomic, readonly, strong) C29User * _Nullable user;
@property (nonatomic, readonly, strong) id <C29SessionCoordinator> _Nullable sessionCoordinator;
@property (nonatomic, readonly, copy) NSString * _Nonnull appGroupIdentifier;
@end

@class C29UserDevice;
enum Key : NSInteger;

SWIFT_CLASS("_TtC9CopperKit7C29User")
@interface C29User : NSObject <NSCoding>
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
@property (nonatomic, copy) NSArray<C29UserDevice *> * _Nonnull devices;
@property (nonatomic, strong) NSDate * _Nullable lastAuthenticationTimestamp;
@property (nonatomic, strong) id <C29SessionDataSource> _Nullable session;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
+ (C29User * _Nullable)fromDictionary:(NSDictionary * _Nonnull)dataDict;
- (id _Nullable)getValue:(enum Key)key;
- (void)setValue:(enum Key)key value:(id _Nullable)value;
- (void)setUserInfo:(C29User * _Nullable)user;
- (void)resetUserData;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
@end

typedef SWIFT_ENUM(NSInteger, Key) {
  KeyId = 0,
  KeyUserId = 1,
  KeyICloudToken = 2,
  KeyLastRequestId = 3,
  KeyRole = 4,
};


@interface C29User (SWIFT_EXTENSION(CopperKit))
@end


@interface C29User (SWIFT_EXTENSION(CopperKit))
@end


@interface C29User (SWIFT_EXTENSION(CopperKit))
@end


SWIFT_CLASS("_TtC9CopperKit13C29UserDevice")
@interface C29UserDevice : NSObject <NSCoding>
@property (nonatomic, readonly, copy) NSString * _Null_unspecified id;
@property (nonatomic, readonly, strong) NSDate * _Null_unspecified timestamp;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified name;
@property (nonatomic, readonly, strong) NSDate * _Null_unspecified lastActive;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified label;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceToken;
@property (nonatomic, readonly, copy) NSString * _Nullable bundleId;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
+ (C29UserDevice * _Nullable)fromDictionary:(NSDictionary * _Nonnull)dataDict;
+ (NSArray<C29UserDevice *> * _Nullable)getDevicesFromDictionary:(NSArray<NSDictionary *> * _Nonnull)dataDict;
- (BOOL)isEqual:(id _Nullable)object;
@end


@interface C29UserDevice (SWIFT_EXTENSION(CopperKit))
@end


SWIFT_CLASS("_TtC9CopperKit11C29UserInfo")
@interface C29UserInfo : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified userId;
@property (nonatomic, readonly, copy) NSString * _Nullable streetOne;
@property (nonatomic, readonly, copy) NSString * _Nullable streetTwo;
@property (nonatomic, readonly, copy) NSString * _Nullable city;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable zip;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nonnull fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable emailAddress;
@property (nonatomic, readonly, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, strong) UIImage * _Nullable avatar;
@property (nonatomic, readonly, strong) NSURL * _Nullable avatarURL;
@property (nonatomic, readonly, copy) NSString * _Nullable username;
- (BOOL)isVerified:(enum C29Scope)scope;
@end


@interface C29UserInfo (SWIFT_EXTENSION(CopperKit))
@end


SWIFT_CLASS("_TtC9CopperKit25C29UserInfoViewController")
@interface C29UserInfoViewController : SFSafariViewController <SFSafariViewControllerDelegate>
- (void)loadView;
- (void)viewDidLoad;
- (void)safariViewController:(SFSafariViewController * _Nonnull)controller didCompleteInitialLoad:(BOOL)didLoadSuccessfully;
- (void)safariViewControllerDidFinish:(SFSafariViewController * _Nonnull)controller;
- (nonnull instancetype)initWithURL:(NSURL * _Nonnull)URL entersReaderIfAvailable:(BOOL)entersReaderIfAvailable OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9CopperKit19C29VerificationCode")
@interface C29VerificationCode : NSObject
@property (nonatomic, copy) NSString * _Nonnull code;
+ (C29VerificationCode * _Nullable)fromDictionary:(NSDictionary * _Nonnull)dataDict;
@end


SWIFT_PROTOCOL("_TtP9CopperKit12CopperRecord_")
@protocol CopperRecord
@property (nonatomic, readonly) enum C29Scope scope;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL verified;
@property (nonatomic, readonly) BOOL valid;
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionary;
@property (nonatomic, readonly, strong) NSDate * _Nullable timestamp;
@property (nonatomic) BOOL uploaded;
@property (nonatomic) BOOL deleted;
@property (nonatomic, readonly) BOOL isBlank;
@end


SWIFT_PROTOCOL("_TtP9CopperKit13CopperAddress_")
@protocol CopperAddress <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable streetOne;
@property (nonatomic, copy) NSString * _Nullable streetTwo;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
@end

@protocol CopperRecordObjectDelegate;

SWIFT_CLASS("_TtC9CopperKit18CopperRecordObject")
@interface CopperRecordObject : NSObject <NSCopying, CopperRecord, NSCoding>
@property (nonatomic) enum C29Scope scope;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL verified;
@property (nonatomic, strong) NSDate * _Nullable timestamp;
@property (nonatomic) BOOL uploaded;
@property (nonatomic) BOOL deleted;
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, strong) id <CopperRecordObjectDelegate> _Nullable delegate;
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionary;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
+ (void)fromDictionary:(enum C29Scope)scope dataDict:(NSDictionary * _Nonnull)dataDict session:(id <C29SessionDataSource> _Nullable)session completion:(void (^ _Nonnull)(CopperRecordObject * _Nullable))completion;
@property (nonatomic, readonly) BOOL valid;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Null_unspecified)zone;
@end


SWIFT_CLASS("_TtC9CopperKit19CopperAddressRecord")
@interface CopperAddressRecord : CopperRecordObject <CopperAddress>
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, copy) NSString * _Nullable streetOne;
@property (nonatomic, copy) NSString * _Nullable streetTwo;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)initWithStreetOne:(NSString * _Null_unspecified)streetOne streetTwo:(NSString * _Null_unspecified)streetTwo city:(NSString * _Null_unspecified)city state:(NSString * _Null_unspecified)state zip:(NSString * _Null_unspecified)zip country:(NSString * _Null_unspecified)country id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


SWIFT_PROTOCOL("_TtP9CopperKit25CopperStringDisplayRecord_")
@protocol CopperStringDisplayRecord
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


@interface CopperAddressRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


SWIFT_PROTOCOL("_TtP9CopperKit12CopperAvatar_")
@protocol CopperAvatar <CopperRecord>
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable url;
- (UIImage * _Nullable)getAvatar;
@end


SWIFT_CLASS("_TtC9CopperKit18CopperAvatarRecord")
@interface CopperAvatarRecord : CopperRecordObject <CopperAvatar>
@property (nonatomic, strong) UIImage * _Nullable image;
- (UIImage * _Nullable)getAvatar;
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
+ (id <CopperAvatar> _Nonnull)getAvatarRecordForInitials:(NSString * _Nonnull)initials session:(id <C29SessionDataSource> _Null_unspecified)session;
@end


SWIFT_PROTOCOL("_TtP9CopperKit15CopperSetRecord_")
@protocol CopperSetRecord <CopperRecord>
@end


SWIFT_CLASS("_TtC9CopperKit20CopperContactsRecord")
@interface CopperContactsRecord : CopperRecordObject <CopperSetRecord>
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionary;
- (nonnull instancetype)init;
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperContactsRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


SWIFT_PROTOCOL("_TtP9CopperKit10CopperDate_")
@protocol CopperDate <CopperRecord>
@property (nonatomic, strong) NSDate * _Nullable date;
@end


SWIFT_CLASS("_TtC9CopperKit16CopperDateRecord")
@interface CopperDateRecord : CopperRecordObject <CopperDate>
@property (nonatomic, strong) NSDate * _Nullable date;
- (nonnull instancetype)initWithDateString:(NSString * _Null_unspecified)dateString id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperDateRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


SWIFT_PROTOCOL("_TtP9CopperKit11CopperEmail_")
@protocol CopperEmail <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable address;
@end


SWIFT_CLASS("_TtC9CopperKit17CopperEmailRecord")
@interface CopperEmailRecord : CopperRecordObject <CopperEmail>
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, copy) NSString * _Nullable address;
- (nonnull instancetype)initWithAddress:(NSString * _Null_unspecified)address id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperEmailRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


SWIFT_PROTOCOL("_TtP9CopperKit10CopperName_")
@protocol CopperName <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable initials;
@end


SWIFT_CLASS("_TtC9CopperKit16CopperNameRecord")
@interface CopperNameRecord : CopperRecordObject <CopperName>
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable initials;
- (nonnull instancetype)initWithFirstName:(NSString * _Null_unspecified)firstName lastName:(NSString * _Null_unspecified)lastName id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperNameRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end

@class NSHTTPURLResponse;

SWIFT_CLASS("_TtC9CopperKit16CopperNetworkAPI")
@interface CopperNetworkAPI : NSObject <C29API>
@property (nonatomic, weak) id <CopperNetworkAPIDelegate> _Nullable delegate;
@property (nonatomic, weak) id <CopperNetworkAPIDataSource> _Nullable dataSource;
@property (nonatomic, copy) NSString * _Nonnull URL;
- (NSError * _Nonnull)handleError:(NSHTTPURLResponse * _Null_unspecified)response dataDict:(NSDictionary * _Null_unspecified)dataDict;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP9CopperKit26CopperNetworkAPIDataSource_")
@protocol CopperNetworkAPIDataSource
- (C29RecordCache * _Nonnull)recordCacheForNetworkAPI:(CopperNetworkAPI * _Nonnull)api;
@end


SWIFT_PROTOCOL("_TtP9CopperKit24CopperNetworkAPIDelegate_")
@protocol CopperNetworkAPIDelegate
- (NSString * _Nullable)authTokenForAPI:(CopperNetworkAPI * _Nonnull)api;
- (id _Nullable)userIdentifierForLoggingErrorsInAPI:(CopperNetworkAPI * _Nonnull)api;
- (void)networkAPI:(CopperNetworkAPI * _Nonnull)api recordAnalyticsEvent:(NSString * _Nonnull)event withParameters:(NSDictionary<NSString *, id> * _Nonnull)parameters;
- (void)networkAPI:(CopperNetworkAPI * _Nonnull)api attemptLoginWithCallback:(void (^ _Nonnull)(BOOL, NSError * _Nullable))callback;
- (void)beganRequestInNetworkAPI:(CopperNetworkAPI * _Nonnull)api;
- (void)endedRequestInNetworkAPI:(CopperNetworkAPI * _Nonnull)api;
@end


SWIFT_CLASS("_TtC9CopperKit29CopperNetworkActivityRegistry")
@interface CopperNetworkActivityRegistry : NSObject
- (void)activityBegan;
- (void)activityEnded;
+ (CopperNetworkActivityRegistry * _Nonnull)sharedRegistry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP9CopperKit11CopperPhone_")
@protocol CopperPhone <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable number;
@property (nonatomic, readonly, strong) UIImage * _Nullable countryImage;
@end

@class NSNumber;

SWIFT_CLASS("_TtC9CopperKit17CopperPhoneRecord")
@interface CopperPhoneRecord : CopperRecordObject <CopperPhone>
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable number;
@property (nonatomic, readonly, strong) UIImage * _Nullable countryImage;
+ (NSString * _Nonnull)DefaultCountryCode;
- (nonnull instancetype)initWithIsoNumber:(NSString * _Null_unspecified)isoNumber id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
+ (NSNumber * _Nullable)getPrefixForCountryCode:(NSString * _Nonnull)countryCode;
+ (NSString * _Nonnull)typeAheadPhoneNumber:(NSString * _Nonnull)phoneNumber;
@end


@interface CopperPhoneRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end




SWIFT_PROTOCOL("_TtP9CopperKit26CopperRecordObjectDelegate_")
@protocol CopperRecordObjectDelegate
- (void)recordWasUpdated:(CopperRecordObject * _Nonnull)record type:(Class <CopperRecord> _Nonnull)type;
@end



SWIFT_PROTOCOL("_TtP9CopperKit15CopperSignature_")
@protocol CopperSignature <CopperRecord>
@property (nonatomic, strong) UIImage * _Nullable signatureImage;
- (UIImage * _Nullable)getImage;
@end


SWIFT_CLASS("_TtC9CopperKit21CopperSignatureRecord")
@interface CopperSignatureRecord : CopperRecordObject <CopperSignature>
@property (nonatomic, strong) UIImage * _Nullable signatureImage;
- (UIImage * _Nullable)getImage;
@property (nonatomic, readonly) BOOL valid;
@end



SWIFT_PROTOCOL("_TtP9CopperKit14CopperUsername_")
@protocol CopperUsername <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable username;
@end


SWIFT_CLASS("_TtC9CopperKit20CopperUsernameRecord")
@interface CopperUsernameRecord : CopperRecordObject <CopperUsername>
@property (nonatomic, copy) NSString * _Nullable username;
- (nonnull instancetype)initWithUsername:(NSString * _Null_unspecified)username id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperUsernameRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


@interface LAContext (SWIFT_EXTENSION(CopperKit))
- (BOOL)copper_canEvaluatePolicy:(LAPolicy)policy error:(NSError * _Nullable * _Null_unspecified)error;
@end


@interface NSDate (SWIFT_EXTENSION(CopperKit))
- (NSString * _Nonnull)toLocalStringWithFormat:(NSString * _Nonnull)dateFormat;
- (BOOL)isPastThreshold:(double)seconds;
@end


@interface NSError (SWIFT_EXTENSION(CopperKit))
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull dictionary;
@end


@interface NSLayoutConstraint (SWIFT_EXTENSION(CopperKit))
@end


@interface NSObject (SWIFT_EXTENSION(CopperKit))
@property (nonatomic, readonly, copy) NSString * _Nonnull className;
@end


@interface NSURLComponents (SWIFT_EXTENSION(CopperKit))
- (NSString * _Nullable)getQueryStringParameter:(NSString * _Nonnull)name;
@end


SWIFT_CLASS("_TtC9CopperKit18TouchAndHoldButton")
@interface TouchAndHoldButton : UIButton
- (void)addTarget:(id _Nonnull)target action:(SEL _Null_unspecified)action timeInterval:(NSTimeInterval)timeInterval;
- (void)sourceTouchUp:(UIButton * _Nonnull)sender;
- (void)sourceTouchDown:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIButton (SWIFT_EXTENSION(CopperKit))
@end


@interface UIColor (SWIFT_EXTENSION(CopperKit))
+ (UIColor * _Nonnull)copper_IdentitySheetBackgroundColor;
+ (UIColor * _Nonnull)copper_IdentitySheetNameColor;
+ (UIColor * _Nonnull)copper_IdentitySheetScopeColor;
+ (UIColor * _Nonnull)copper_IdentitySheetValueColor;
+ (UIColor * _Nonnull)copper_IdentitySheetTintColor;
+ (UIColor * _Nonnull)copper_IdentitySheetEditTextColor;
+ (UIColor * _Nonnull)copper_IdentitySheetTextInputPlaceholderTextColor;
+ (UIColor * _Nonnull)copper_IdentitySheetBorderColor;
+ (UIColor * _Nonnull)copper_IdentitySheetEditAvatarIconColor;
+ (UIColor * _Nonnull)copper_IdentitySheetSwitchColor;
+ (UIColor * _Nonnull)copper_IdentitySheetToggleValueLabelEnabledColor;
+ (UIColor * _Nonnull)copper_IdentitySheetToggleValueLabelDisabledColor;
+ (UIColor * _Nonnull)copper_IdentitySheetSwitchBackgroundColor;
+ (UIColor * _Nonnull)copper_IdentitySheetAvatarShadowColor;
+ (UIColor * _Nonnull)copper_IdentitySheetSettingsButtonColor;
+ (UIColor * _Nonnull)copper_DefaultAvatarIconColor;
+ (UIColor * _Nonnull)copper_IdentitySheetAvatarShadowViewBackgroundColor;
+ (UIColor * _Nonnull)copper_CardHeaderArrowColor;
+ (UIColor * _Nonnull)copper_CardHeaderTitleColor;
+ (UIColor * _Nonnull)copper_CardHeaderSubtitleColor;
+ (UIColor * _Nonnull)copper_ClientBackgroundColor;
+ (UIColor * _Nonnull)copper_ClientNameLabelColor;
+ (UIColor * _Nonnull)copper_ClientSecondaryLabelColor;
+ (UIColor * _Nonnull)copper_ApplicationCardIconBorderColor;
+ (UIColor * _Nonnull)copper_RequestSheetBackgroundColor;
+ (UIColor * _Nonnull)copper_RequestSheetBackgroundColorOverlay;
+ (UIColor * _Nonnull)copper_RequestSheetTableViewBackgroundColor;
+ (UIColor * _Nonnull)copper_RequestSheetBorderColor;
+ (UIColor * _Nonnull)copper_CopperRequestHeaderCloseButtonTintColor;
+ (UIColor * _Nonnull)copper_CopperRequestHeaderApplicationNameColor;
+ (UIColor * _Nonnull)copper_RequestSheetTableViewHeaderBackgroundColor;
+ (UIColor * _Nonnull)copper_RequestViewControllerQuickSelectDefaultColor;
+ (UIColor * _Nonnull)copper_RequestViewControllerQuickSelectSelectedColor;
+ (UIColor * _Nonnull)copper_RequestSheetHeaderTextColor;
+ (UIColor * _Nonnull)copper_RequestSheetValueColor;
+ (UIColor * _Nonnull)copper_RequestSheetTextInputPlaceholderTextColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenLabelColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenLabelDisabledColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonDismissedColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonSendingColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonSuccessColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonSendingBorderColor;
+ (UIColor * _Nonnull)copper_RequestViewControllerOpenButtonGradientTop;
+ (UIColor * _Nonnull)copper_RequestViewControllerOpenButtonGradientBottom;
+ (UIColor * _Nonnull)copper_SettingsBackgroundColor;
+ (UIColor * _Nonnull)copper_SettingsSectionHeaderColor;
+ (UIColor * _Nonnull)copper_SettingsCellTitleTextColor;
+ (UIColor * _Nonnull)copper_SettingsCellSecondaryTextColor;
+ (UIColor * _Nonnull)copper_SettingsSeparatorViewColor;
+ (UIColor * _Nonnull)copper_SettingsTableViewFooterVersionColor;
+ (UIColor * _Nonnull)copper_SettingsTableViewNavBarTextColor;
+ (UIColor * _Nonnull)copper_SettngsTableViewNavigationControllerBackColor;
+ (UIColor * _Nonnull)copper_ContactsPickerTextColor;
+ (UIColor * _Nonnull)copper_ContactsPickerTintColor;
+ (UIColor * _Nonnull)copper_ContactsPickerViewBackgroundColor;
+ (UIColor * _Nonnull)copper_ContactsPickerPlaceholderTextColor;
+ (UIColor * _Nonnull)copper_ContactsPickerNavBarTintColor;
+ (UIColor * _Nonnull)copper_ContactsPickerHeaderBackgroundColor;
+ (UIColor * _Nonnull)copper_OnboardingViewTextColor;
+ (UIColor * _Nonnull)copper_OnboardingViewSubTextColor;
+ (UIColor * _Nonnull)copper_OnboardingViewContinueButtonTextColor;
+ (UIColor * _Nonnull)copper_OnboardingViewContinueButtonColor;
+ (UIColor * _Nonnull)copper_OnboardingViewLegalButtonTextColor;
+ (UIColor * _Nonnull)copper_OnboardingViewShadowGradientTopColor;
+ (UIColor * _Nonnull)copper_OnboardingViewShadowGradientBottomColor;
+ (UIColor * _Nonnull)copper_RegistrationViewBackgroundColor;
+ (UIColor * _Nonnull)copper_RegistrationViewPrimaryTextColor;
+ (UIColor * _Nonnull)copper_RegistrationViewSecondaryTextColor;
+ (UIColor * _Nonnull)copper_RegistrationViewErrorTextColor;
+ (UIColor * _Nonnull)copper_RegistrationViewBorderColor;
+ (UIColor * _Nonnull)copper_RegistrationViewSuccessColor;
+ (UIColor * _Nonnull)copper_RegistrationViewNumberPadHightlightColor;
+ (UIColor * _Nonnull)copper_RegistrationViewSendButtonColor;
+ (UIColor * _Nonnull)copper_IdentityCellKeyboardToolbarTintColor;
+ (UIColor * _Nonnull)copper_RegistrationColor;
+ (UIColor * _Nonnull)copper_ActivityIndicatorBackgroundColor;
+ (UIColor * _Nonnull)copper_AuthenticationControllerTitleColor;
+ (UIColor * _Nonnull)copper_AuthenticationControllerTextViewColor;
+ (UIColor * _Nonnull)copper_AuthenticationControllerButtonDefaultColor;
+ (UIColor * _Nonnull)copper_AuthenticationControllerButtonDisabledColor;
+ (UIColor * _Nonnull)copper_DocumentViewControllerPrimaryColor;
+ (UIColor * _Nonnull)copper_DocumentViewControllerNetworkIndicatorColor;
+ (UIColor * _Nonnull)copper_DocumentViewControllerNavBarColor;
+ (UIColor * _Nonnull)copper_DocumentViewControllerNavBarBottomColor;
+ (UIColor * _Nonnull)copper_ModalCardChromeBackgroundColor;
+ (UIColor * _Nonnull)copper_ModalCardBackgroundColor;
+ (UIColor * _Nonnull)copper_ModalCardTitleColor;
+ (UIColor * _Nonnull)copper_ModalCardSubTextColor;
+ (UIColor * _Nonnull)copper_ModalCardActionButtonBackgroundColor;
+ (UIColor * _Nonnull)copper_ModalCardActionButtonTextColor;
+ (UIColor * _Nonnull)copper_ModalCardCloseButtonTextColor;
+ (UIColor * _Nonnull)copper_ModalCardImageShadowColor;
+ (UIColor * _Nonnull)copper_primaryCopper;
+ (UIColor * _Nonnull)copper_primaryGreen;
+ (UIColor * _Nonnull)copper_primaryVerdigris;
+ (UIColor * _Nonnull)copper_midnightGrey;
+ (UIColor * _Nonnull)copper_secondaryBlue;
+ (UIColor * _Nonnull)copper_secondaryPurple;
+ (UIColor * _Nonnull)copper_secondaryPink;
+ (UIColor * _Nonnull)copper_secondaryRed;
+ (UIColor * _Nonnull)copper_secondaryOrange;
+ (UIColor * _Nonnull)copper_secondaryYellow;
+ (UIColor * _Nonnull)copper_softGreen;
+ (UIColor * _Nonnull)copper_softBlue;
+ (UIColor * _Nonnull)copper_softPurple;
+ (UIColor * _Nonnull)copper_softPink;
+ (UIColor * _Nonnull)copper_softOrange;
+ (UIColor * _Nonnull)copper_softYellow;
+ (UIColor * _Nonnull)copper_darkGreen;
+ (UIColor * _Nonnull)copper_darkBlue;
+ (UIColor * _Nonnull)copper_darkPurple;
+ (UIColor * _Nonnull)copper_darkBrown;
+ (UIColor * _Nonnull)copper_black;
+ (UIColor * _Nonnull)copper_black92;
+ (UIColor * _Nonnull)copper_black60;
+ (UIColor * _Nonnull)copper_black40;
+ (UIColor * _Nonnull)copper_black20;
+ (UIColor * _Nonnull)copper_black08;
+ (UIColor * _Nonnull)copper_white;
+ (UIColor * _Nonnull)copper_white95;
+ (UIColor * _Nonnull)copper_white72;
+ (UIColor * _Nonnull)copper_white52;
+ (UIColor * _Nonnull)copper_white32;
+ (UIColor * _Nonnull)copper_white20;
+ (UIColor * _Nonnull)hexStringToUIColor:(NSString * _Nonnull)hex;

/// Hex string of a UIColor instance.
///
/// \param rgba Whether the alpha should be included.
- (NSString * _Nonnull)hexString:(BOOL)includeAlpha;
@end


@interface UIFont (SWIFT_EXTENSION(CopperKit))
+ (UIFont * _Nonnull)C29_Body;
+ (UIFont * _Nonnull)C29_H2;
+ (UIFont * _Nonnull)C29_H3;
+ (UIFont * _Nonnull)C29_H4;
+ (UIFont * _Nonnull)copper_SectionHeaderFont;
+ (UIFont * _Nonnull)copper_PrimaryFont;
+ (UIFont * _Nonnull)copper_PrimaryItalicsFont;
+ (UIFont * _Nonnull)copper_SecondaryFont;
+ (UIFont * _Nonnull)copper_IdentitySheetNameFont;
+ (UIFont * _Nonnull)copper_IdentitySheetToggleValueLabelFont;
+ (UIFont * _Nonnull)copper_ClientIconFont;
+ (UIFont * _Nonnull)copper_RequestSheetHeaderNameFont;
+ (UIFont * _Nonnull)copper_RequestSheetOpenWithCopperFont;
+ (UIFont * _Nonnull)copper_CardHeaderTitleFont;
+ (UIFont * _Nonnull)copper_CardHeaderSubtitleFont;
+ (UIFont * _Nonnull)copper_SettingsTableSectionHeaderFont;
+ (UIFont * _Nonnull)copper_SettingsTableViewFooterVersionFont;
+ (UIFont * _Nonnull)copper_SettingsTableViewNavigationControllerFont;
+ (UIFont * _Nonnull)copper_SettingsTableViewCellSecondaryTextFont;
+ (UIFont * _Nonnull)copper_SettingsTableViewNavigationControllerBackFont;
+ (UIFont * _Nonnull)copper_CopperContactsPickerCellFont;
+ (UIFont * _Nonnull)copper_ContactsPickerNavigationBarFont;
+ (UIFont * _Nonnull)copper_ContactsPickerNavigationButtonFont;
+ (UIFont * _Nonnull)copper_OnboardingViewTextFont;
+ (UIFont * _Nonnull)copper_OnboardingViewSubTextFont;
+ (UIFont * _Nonnull)copper_OnboardingViewContinueButtonFont;
+ (UIFont * _Nonnull)copper_OnboardingViewLegalButtonFont;
+ (UIFont * _Nonnull)copper_RegistrationViewSuccessMessageFont;
+ (UIFont * _Nonnull)copper_RegistrationViewControlPlaceholderFont;
+ (UIFont * _Nonnull)copper_RegistrationViewControlLabelFont;
+ (UIFont * _Nonnull)copper_RegistrationViewNumberPadFont;
+ (UIFont * _Nonnull)copper_RegistrationViewNumberPadPressedFont;
+ (UIFont * _Nonnull)copper_DocumentViewerNavBarFont;
@end

@class UIView;
@class UIImageView;

@interface UIImage (SWIFT_EXTENSION(CopperKit))
+ (UIImage * _Nonnull)toImage:(UIView * _Nonnull)view;
+ (UIImage * _Nonnull)crop:(UIImage * _Nonnull)image rect:(CGRect)rect;
+ (void)c29_imageFromUrl:(NSString * _Nonnull)url callback:(void (^ _Nonnull)(UIImage * _Nullable))callback;
+ (CGSize)newSizeFromHeight:(UIImage * _Nonnull)image newHeight:(CGFloat)newHeight;
+ (UIImage * _Nonnull)imageWithImage:(UIImage * _Nonnull)image newSize:(CGSize)newSize;
- (UIImage * _Nonnull)roundImage;
+ (UIImage * _Nonnull)c29_pixelWithColor:(UIColor * _Nonnull)color;
+ (void)pulseImageView:(UIImageView * _Nonnull)imageView repeat:(BOOL)repeat;
@end

@class NSIndexPath;

@interface UITableView (SWIFT_EXTENSION(CopperKit))
- (UITableView * _Nullable)getTableView;
- (BOOL)isVisible:(NSIndexPath * _Nonnull)indexPath;
@property (nonatomic, readonly, strong) NSIndexPath * _Nonnull indexPathForLastCell;
@end


@interface UITextField (SWIFT_EXTENSION(CopperKit))
- (void)setPlaceholderColor:(UIColor * _Nonnull)color;
@end


@interface UITextView (SWIFT_EXTENSION(CopperKit))
- (void)boldSubstring:(NSString * _Nonnull)substr;
@end


@interface UIView (SWIFT_EXTENSION(CopperKit))
- (NSArray<UIView *> * _Nonnull)addBorderWithEdges:(UIRectEdge)edges color:(UIColor * _Nonnull)color thickness:(CGFloat)thickness bottomLeftInset:(CGFloat)bottomLeftInset;
- (void)addGradient:(UIColor * _Nonnull)topColor bottomColor:(UIColor * _Nonnull)bottomColor;
- (void)shakeWithConstraint:(NSLayoutConstraint * _Nonnull)constraint withShakeDistance:(CGFloat)distance animationDuration:(double)animationDuration times:(NSInteger)times state:(NSInteger)state callback:(void (^ _Null_unspecified)(void))callback;
- (void)noticeWiggleWithConstant:(NSLayoutConstraint * _Nonnull)constraint withWiggleDistance:(CGFloat)withWiggleDistance animationDuration:(double)animationDuration completion:(void (^ _Null_unspecified)(void))completion;
@end

#pragma clang diagnostic pop
