// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import SafariServices;
@import UIKit;
@import WebKit;
@import LocalAuthentication;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@protocol CopperRecord;

SWIFT_PROTOCOL("_TtP9CopperKit24C29ApplicationDataSource_")
@protocol C29ApplicationDataSource
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSArray<id <CopperRecord>> * _Nonnull records;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nullable logoUri;
@property (nonatomic, readonly, copy) NSString * _Nullable url;
@property (nonatomic, readonly, copy) NSString * _Nullable redirectUri;
@end

@class UIColor;
@class NSCoder;

SWIFT_CLASS("_TtC9CopperKit11Application")
@interface Application : NSObject <C29ApplicationDataSource, NSCoding>
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSArray<id <CopperRecord>> * _Nonnull records;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nullable logoUri;
@property (nonatomic, strong) UIColor * _Nullable color;
@property (nonatomic, copy) NSString * _Nullable url;
@property (nonatomic, copy) NSString * _Nullable redirectUri;
- (nonnull instancetype)initWithApplicationId:(NSString * _Nonnull)applicationId name:(NSString * _Nonnull)name records:(NSArray<id <CopperRecord>> * _Nonnull)records OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
@end


@interface Application (SWIFT_EXTENSION(CopperKit))
@end

@class NSURL;

SWIFT_CLASS("_TtC9CopperKit14C29Application")
@interface C29Application : NSObject
+ (C29Application * _Nonnull)sharedInstance;
- (void)configureWithOauthToken:(NSString * _Nonnull)token;
- (void)closeSession;
- (BOOL)openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface C29Application (SWIFT_EXTENSION(CopperKit))
@end


@interface C29Application (SWIFT_EXTENSION(CopperKit))
@end


@protocol CopperAvatar;
@protocol CopperName;
@protocol CopperAddress;
@protocol CopperEmail;
@protocol CopperPhone;
@protocol CopperUsername;
@protocol CopperDate;
@protocol CopperSignature;
enum C29Scope : NSInteger;

SWIFT_PROTOCOL("_TtP9CopperKit21C29IdentityDataSource_")
@protocol C29IdentityDataSource
@property (nonatomic, strong) id <CopperAvatar> _Nullable avatar;
@property (nonatomic, strong) id <CopperName> _Nullable name;
@property (nonatomic, strong) id <CopperAddress> _Nullable address;
@property (nonatomic, strong) id <CopperEmail> _Nullable email;
@property (nonatomic, strong) id <CopperPhone> _Nullable phone;
@property (nonatomic, strong) id <CopperUsername> _Nullable username;
@property (nonatomic, strong) id <CopperDate> _Nullable birthday;
@property (nonatomic, strong) id <CopperSignature> _Nullable signature;
- (id <CopperRecord> _Nullable)getDefaultOrBlank:(enum C29Scope)scope;
- (void)addOrUpdateRecord:(id <CopperRecord> _Nonnull)record;
- (void)removeRecord:(id <CopperRecord> _Nonnull)record;
- (void)sync:(NSArray<id <CopperRecord>> * _Nonnull)record;
- (void)save:(BOOL)forceUpload callback:(void (^ _Nonnull)(BOOL))callback;
- (void)reload;
@end

@class NSDate;
@class C29RequestPlatform;

SWIFT_PROTOCOL("_TtP9CopperKit20C29RequestDataSource_")
@protocol C29RequestDataSource
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull applicationId;
@property (nonatomic, readonly) BOOL expired;
@property (nonatomic, readonly, strong) NSDate * _Nonnull timestamp;
@property (nonatomic, readonly, copy) NSString * _Nullable scopesString;
@property (nonatomic, readonly, strong) C29RequestPlatform * _Nullable platform;
@property (nonatomic, readonly) NSInteger status;
@property (nonatomic, readonly) BOOL responded;
@property (nonatomic, readonly) BOOL complete;
@property (nonatomic, copy) NSArray<id <CopperRecord>> * _Nonnull records;
@end


SWIFT_CLASS("_TtC9CopperKit10C29Request")
@interface C29Request : NSObject <C29RequestDataSource, NSCoding>
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, strong) NSDate * _Nonnull timestamp;
@property (nonatomic, copy) NSString * _Nonnull applicationId;
@property (nonatomic, copy) NSString * _Nullable scopesString;
@property (nonatomic, strong) C29RequestPlatform * _Nullable platform;
@property (nonatomic) NSInteger status;
@property (nonatomic, copy) NSArray<id <CopperRecord>> * _Nonnull records;
@property (nonatomic, readonly) BOOL responded;
@property (nonatomic, readonly) BOOL expired;
@property (nonatomic, readonly) BOOL complete;
- (nonnull instancetype)initWithRequestData:(id <C29RequestDataSource> _Nonnull)requestData;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
@end


@interface C29Request (SWIFT_EXTENSION(CopperKit))
@end


@interface C29Request (SWIFT_EXTENSION(CopperKit))
@end


@class NSDictionary;

SWIFT_CLASS("_TtC9CopperKit15C29RequestGrant")
@interface C29RequestGrant : NSObject
+ (C29RequestGrant * _Nullable)fromDictionary:(NSDictionary * _Nonnull)dataDict;
@end


SWIFT_CLASS("_TtC9CopperKit18C29RequestPlatform")
@interface C29RequestPlatform : NSObject <NSCoding>
- (nonnull instancetype)initWithType:(NSString * _Nonnull)type version:(NSString * _Nonnull)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
@end

typedef SWIFT_ENUM(NSInteger, C29RequestStatus) {
  C29RequestStatusApproved = 1,
  C29RequestStatusDismissed = 0,
  C29RequestStatusReported = -1,
  C29RequestStatusUnanswered = -29,
};

typedef SWIFT_ENUM(NSInteger, C29Scope) {
  C29ScopeNull = -1,
  C29ScopeName = 1000,
  C29ScopeAvatar = 1001,
  C29ScopePhone = 1002,
  C29ScopeEmail = 1003,
  C29ScopeUsername = 1004,
  C29ScopeAddress = 1005,
  C29ScopeBirthday = 1006,
  C29ScopeSignature = 1007,
  C29ScopeContactsFavorites = 3001,
};


SWIFT_CLASS("_TtC9CopperKit17C29SecureSettings")
@interface C29SecureSettings : NSObject
@property (nonatomic, copy) NSString * _Nullable secret;
@property (nonatomic, copy) NSString * _Nullable authToken;
@property (nonatomic, copy) NSString * _Nullable passcode;
@property (nonatomic, copy) NSString * _Nullable aesKey;
@property (nonatomic, copy) NSString * _Nullable aesIV;
@end


@interface C29SecureSettings (SWIFT_EXTENSION(CopperKit))
@end

@class UIImage;
@class NSError;

SWIFT_CLASS("_TtC9CopperKit11C29UserInfo")
@interface C29UserInfo : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified userId;
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nonnull fullName;
@property (nonatomic, readonly, copy) NSString * _Nullable emailAddress;
@property (nonatomic, readonly, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, strong) UIImage * _Nullable avatar;
@property (nonatomic, readonly, strong) NSURL * _Nullable avatarURL;
@property (nonatomic, readonly, copy) NSString * _Nullable username;
+ (void)fromDictionary:(NSString * _Nonnull)jwt dataDict:(NSDictionary * _Nullable)dataDict callback:(void (^ _Nonnull)(C29UserInfo * _Nullable, NSError * _Nullable))callback;
@end


@interface C29UserInfo (SWIFT_EXTENSION(CopperKit))
@end


SWIFT_CLASS("_TtC9CopperKit17C29ViewController")
@interface C29ViewController : SFSafariViewController <SFSafariViewControllerDelegate>
- (void)loadView;
- (void)viewDidLoad;
- (void)safariViewController:(SFSafariViewController * _Nonnull)controller didCompleteInitialLoad:(BOOL)didLoadSuccessfully;
- (void)safariViewControllerDidFinish:(SFSafariViewController * _Nonnull)controller;
- (nonnull instancetype)initWithURL:(NSURL * _Nonnull)URL entersReaderIfAvailable:(BOOL)entersReaderIfAvailable OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP9CopperKit12CopperRecord_")
@protocol CopperRecord
@property (nonatomic, readonly) enum C29Scope scope;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL verified;
@property (nonatomic, readonly) BOOL valid;
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionary;
@property (nonatomic, readonly, strong) NSDate * _Nullable timestamp;
@property (nonatomic) BOOL uploaded;
@property (nonatomic) BOOL deleted;
@property (nonatomic, readonly) BOOL isBlank;
@end


SWIFT_PROTOCOL("_TtP9CopperKit13CopperAddress_")
@protocol CopperAddress <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable streetOne;
@property (nonatomic, copy) NSString * _Nullable streetTwo;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
@end

@protocol CopperRecordObjectDelegate;

SWIFT_CLASS("_TtC9CopperKit18CopperRecordObject")
@interface CopperRecordObject : NSObject <NSCopying, CopperRecord, NSCoding>
@property (nonatomic) enum C29Scope scope;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL verified;
@property (nonatomic, strong) NSDate * _Nullable timestamp;
@property (nonatomic) BOOL uploaded;
@property (nonatomic) BOOL deleted;
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, strong) id <CopperRecordObjectDelegate> _Nullable delegate;
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionary;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
@property (nonatomic, readonly) BOOL valid;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Null_unspecified)zone;
@end


SWIFT_CLASS("_TtC9CopperKit19CopperAddressRecord")
@interface CopperAddressRecord : CopperRecordObject <CopperAddress>
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, copy) NSString * _Nullable streetOne;
@property (nonatomic, copy) NSString * _Nullable streetTwo;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)initWithStreetOne:(NSString * _Null_unspecified)streetOne streetTwo:(NSString * _Null_unspecified)streetTwo city:(NSString * _Null_unspecified)city state:(NSString * _Null_unspecified)state zip:(NSString * _Null_unspecified)zip country:(NSString * _Null_unspecified)country id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


SWIFT_PROTOCOL("_TtP9CopperKit25CopperStringDisplayRecord_")
@protocol CopperStringDisplayRecord
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


@interface CopperAddressRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


SWIFT_CLASS("_TtC9CopperKit22CopperApplicationCache")
@interface CopperApplicationCache : NSObject <NSCoding>
+ (NSString * _Nonnull)C29ApplicationCacheRefreshNotification;
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (NSArray<id <C29ApplicationDataSource>> * _Nonnull)getApplications;
- (id <C29ApplicationDataSource> _Nullable)getApplication:(NSString * _Nonnull)applicationId;
- (void)push:(Application * _Nonnull)application;
- (void)remove:(id <C29ApplicationDataSource> _Nonnull)application;
- (void)update:(Application * _Nonnull)replace add:(Application * _Nonnull)add;
- (void)setApplications:(NSArray<Application *> * _Nonnull)applications;
- (void)removeAll;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface CopperApplicationCache (SWIFT_EXTENSION(CopperKit))
@end


@interface CopperApplicationCache (SWIFT_EXTENSION(CopperKit))
- (void)set:(CopperApplicationCache * _Nonnull)cache;
@end


SWIFT_PROTOCOL("_TtP9CopperKit12CopperAvatar_")
@protocol CopperAvatar <CopperRecord>
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable url;
@end


SWIFT_CLASS("_TtC9CopperKit18CopperAvatarRecord")
@interface CopperAvatarRecord : CopperRecordObject <CopperAvatar>
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


SWIFT_PROTOCOL("_TtP9CopperKit15CopperSetRecord_")
@protocol CopperSetRecord <CopperRecord>
@end


SWIFT_CLASS("_TtC9CopperKit20CopperContactsRecord")
@interface CopperContactsRecord : CopperRecordObject <CopperSetRecord>
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionary;
- (nonnull instancetype)init;
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperContactsRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


SWIFT_PROTOCOL("_TtP9CopperKit10CopperDate_")
@protocol CopperDate <CopperRecord>
@property (nonatomic, strong) NSDate * _Nullable date;
@end


SWIFT_CLASS("_TtC9CopperKit16CopperDateRecord")
@interface CopperDateRecord : CopperRecordObject <CopperDate>
@property (nonatomic, strong) NSDate * _Nullable date;
- (nonnull instancetype)initWithDateString:(NSString * _Null_unspecified)dateString id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperDateRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


SWIFT_PROTOCOL("_TtP9CopperKit11CopperEmail_")
@protocol CopperEmail <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable address;
@end


SWIFT_CLASS("_TtC9CopperKit17CopperEmailRecord")
@interface CopperEmailRecord : CopperRecordObject <CopperEmail>
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, copy) NSString * _Nullable address;
- (nonnull instancetype)initWithAddress:(NSString * _Null_unspecified)address id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperEmailRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


SWIFT_CLASS("_TtC9CopperKit16CopperImageCache")
@interface CopperImageCache : NSObject <NSCoding>
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (void)getImage:(NSString * _Nonnull)url cacheOnDownload:(BOOL)cacheOnDownload callback:(void (^ _Nonnull)(UIImage * _Nullable))callback;
- (void)update:(UIImage * _Nullable)image forUrl:(NSString * _Nonnull)forUrl;
- (void)remove:(NSString * _Nonnull)url;
- (void)removeAll;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface CopperImageCache (SWIFT_EXTENSION(CopperKit))
@end


@interface CopperImageCache (SWIFT_EXTENSION(CopperKit))
- (void)set:(CopperImageCache * _Nonnull)cache;
@end

@class WKUserContentController;
@class WKScriptMessage;
@class NSBundle;

SWIFT_CLASS("_TtC9CopperKit23CopperKitViewController")
@interface CopperKitViewController : UIViewController <WKScriptMessageHandler>
+ (void)login:(UIViewController * _Nonnull)viewController withApplicationId:(NSString * _Nonnull)applicationId scopes:(NSString * _Nonnull)scopes completion:(void (^ _Nonnull)(BOOL, NSDictionary * _Nullable))completion;
@property (nonatomic, strong) NSURL * _Nullable url;
- (void)loadView;
- (void)viewDidLoad;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSString *, id> * _Nullable)change context:(void * _Null_unspecified)context;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP9CopperKit10CopperName_")
@protocol CopperName <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@end


SWIFT_CLASS("_TtC9CopperKit16CopperNameRecord")
@interface CopperNameRecord : CopperRecordObject <CopperName>
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
- (nonnull instancetype)initWithFirstName:(NSString * _Null_unspecified)firstName lastName:(NSString * _Null_unspecified)lastName id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperNameRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end

@class NSData;

SWIFT_CLASS("_TtC9CopperKit16CopperNetworkAPI")
@interface CopperNetworkAPI : NSObject
@property (nonatomic) NSInteger baseURLSetting;
- (void)getJWT:(NSString * _Nonnull)userId secret:(NSString * _Nonnull)secret callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getUserInfo:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)oauthAuthorize:(NSString * _Nonnull)userId applicationId:(NSString * _Nonnull)applicationId redirectUri:(NSString * _Nonnull)redirectUri nonce:(NSString * _Nonnull)nonce state:(NSString * _Nonnull)state scope:(NSString * _Nonnull)scope responseMode:(NSString * _Nonnull)responseMode responseType:(NSString * _Nonnull)responseType callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getURLforCode:(NSString * _Nonnull)userId code:(NSString * _Nonnull)code callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getUserWithID:(NSString * _Nonnull)userID callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)deleteUserWithUserID:(NSString * _Nonnull)userID secret:(NSString * _Nonnull)secret callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getVerificationCode:(NSString * _Nonnull)toPhoneNumber secret:(NSString * _Nonnull)secret callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)saveUserRecordsForUserID:(NSString * _Nonnull)userID records:(NSArray<id <CopperRecord>> * _Nonnull)records callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getUserRecordsForUserID:(NSString * _Nonnull)userID since:(NSDate * _Nullable)since callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)deleteUserRecordsForUserID:(NSString * _Nonnull)userId records:(NSArray<id <CopperRecord>> * _Nonnull)records callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getUserApplicationsForUserID:(NSString * _Nonnull)userID callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getUserApplicationForUserID:(NSString * _Nonnull)userID applicationId:(NSString * _Nonnull)applicationId callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)deleteUserApplicationForUserID:(NSString * _Nonnull)userId applicationId:(NSString * _Nonnull)applicationId callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getUserDevicesForUserID:(NSString * _Nonnull)userID deviceId:(NSString * _Nullable)deviceId callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getUserDeviceForUserID:(NSString * _Nonnull)userID deviceId:(NSString * _Nonnull)deviceId callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)deleteUserDeviceForUserID:(NSString * _Nonnull)userId deviceId:(NSString * _Nonnull)deviceId callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)getRequestForUserID:(NSString * _Nonnull)userId requestId:(NSString * _Nonnull)requestId callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)setRequestGrantForUserID:(NSString * _Nonnull)userId request:(C29Request * _Nonnull)request status:(enum C29RequestStatus)status records:(NSArray<id <CopperRecord>> * _Nonnull)records forceRecordUpload:(BOOL)forceRecordUpload callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)setRequestAckForUserID:(NSString * _Nonnull)userID request:(C29Request * _Nonnull)request callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)saveUserApplicationRecordsForUserID:(NSString * _Nonnull)userId applicationId:(NSString * _Nonnull)applicationId records:(NSArray<id <CopperRecord>> * _Nonnull)records callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)deleteUserApplicationRecordsForUserID:(NSString * _Nonnull)userId applicationId:(NSString * _Nonnull)applicationId records:(NSArray<id <CopperRecord>> * _Nonnull)records callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (void)createBytes:(NSString * _Nonnull)userID fileID:(NSString * _Nonnull)fileID file:(NSData * _Nonnull)file callback:(void (^ _Nonnull)(id _Nullable, NSError * _Nullable))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9CopperKit29CopperNetworkActivityRegistry")
@interface CopperNetworkActivityRegistry : NSObject
- (void)activityBegan;
- (void)activityEnded;
+ (CopperNetworkActivityRegistry * _Nonnull)sharedRegistry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP9CopperKit11CopperPhone_")
@protocol CopperPhone <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable number;
@property (nonatomic, readonly, strong) UIImage * _Nullable countryImage;
@end

@class NSNumber;

SWIFT_CLASS("_TtC9CopperKit17CopperPhoneRecord")
@interface CopperPhoneRecord : CopperRecordObject <CopperPhone>
@property (nonatomic, readonly) BOOL isBlank;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable number;
@property (nonatomic, readonly, strong) UIImage * _Nullable countryImage;
+ (NSString * _Nonnull)DefaultCountryCode;
- (nonnull instancetype)initWithIsoNumber:(NSString * _Null_unspecified)isoNumber id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
+ (NSNumber * _Nullable)getPrefixForCountryCode:(NSString * _Nonnull)countryCode;
+ (NSString * _Nonnull)typeAheadPhoneNumber:(NSString * _Nonnull)phoneNumber;
@end


@interface CopperPhoneRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end



SWIFT_CLASS("_TtC9CopperKit17CopperRecordCache")
@interface CopperRecordCache : NSObject <NSCoding>
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
@property (nonatomic, strong) NSDate * _Nullable lastServerSyncTimestamp;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (id <CopperRecord> _Nullable)getRecord:(enum C29Scope)scope includeDeleted:(BOOL)includeDeleted;
- (NSArray<id <CopperRecord>> * _Nonnull)getAllRecords:(BOOL)includeDeleted;
- (void)add:(id <CopperRecord> _Nonnull)record;
- (void)remove:(enum C29Scope)scope;
- (NSString * _Nonnull)getNextRecordId;
- (void)removeAll;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (void)removeAllInvalid;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface CopperRecordCache (SWIFT_EXTENSION(CopperKit))
- (void)set:(CopperRecordCache * _Nonnull)cache;
@end


@interface CopperRecordCache (SWIFT_EXTENSION(CopperKit))
@end



SWIFT_PROTOCOL("_TtP9CopperKit26CopperRecordObjectDelegate_")
@protocol CopperRecordObjectDelegate
- (void)recordWasUpdated:(CopperRecordObject * _Nonnull)record type:(Class <CopperRecord> _Nonnull)type;
@end



SWIFT_PROTOCOL("_TtP9CopperKit15CopperSignature_")
@protocol CopperSignature <CopperRecord>
@property (nonatomic, strong) UIImage * _Nullable signatureImage;
- (UIImage * _Nullable)getImage;
@end


SWIFT_CLASS("_TtC9CopperKit21CopperSignatureRecord")
@interface CopperSignatureRecord : CopperRecordObject <CopperSignature>
@property (nonatomic, strong) UIImage * _Nullable signatureImage;
- (UIImage * _Nullable)getImage;
@property (nonatomic, readonly) BOOL valid;
@end



SWIFT_PROTOCOL("_TtP9CopperKit14CopperUsername_")
@protocol CopperUsername <CopperRecord>
@property (nonatomic, copy) NSString * _Nullable username;
@end


SWIFT_CLASS("_TtC9CopperKit20CopperUsernameRecord")
@interface CopperUsernameRecord : CopperRecordObject <CopperUsername>
@property (nonatomic, copy) NSString * _Nullable username;
- (nonnull instancetype)initWithUsername:(NSString * _Null_unspecified)username id:(NSString * _Nonnull)id verified:(BOOL)verified;
@property (nonatomic, readonly) BOOL valid;
@end


@interface CopperUsernameRecord (SWIFT_EXTENSION(CopperKit)) <CopperStringDisplayRecord>
@property (nonatomic, readonly, copy) NSString * _Nonnull displayString;
@end


@interface LAContext (SWIFT_EXTENSION(CopperKit))
- (BOOL)copper_canEvaluatePolicy:(LAPolicy)policy error:(NSError * _Nullable * _Null_unspecified)error;
@end


@interface NSDate (SWIFT_EXTENSION(CopperKit))
- (NSString * _Nonnull)toLocalStringWithFormat:(NSString * _Nonnull)dateFormat;
@end


@interface NSError (SWIFT_EXTENSION(CopperKit))
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull dictionary;
@end


@interface NSLayoutConstraint (SWIFT_EXTENSION(CopperKit))
@end


@interface NSObject (SWIFT_EXTENSION(CopperKit))
@property (nonatomic, readonly, copy) NSString * _Nonnull className;
@end


@interface NSURLComponents (SWIFT_EXTENSION(CopperKit))
- (NSString * _Nullable)getQueryStringParameter:(NSString * _Nonnull)name;
@end


SWIFT_CLASS("_TtC9CopperKit12RequestStack")
@interface RequestStack : NSObject <NSCoding>
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (void)push:(id <C29RequestDataSource> _Nonnull)request display:(BOOL)display;
- (C29Request * _Nullable)pop;
- (void)addResponded:(id <C29RequestDataSource> _Nonnull)request;
- (BOOL)isResponded:(NSString * _Nonnull)requestId;
- (id <C29RequestDataSource> _Nullable)getRequest:(NSString * _Nonnull)requestId;
- (BOOL)contains:(NSString * _Nonnull)requestId;
- (void)removeAll;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface RequestStack (SWIFT_EXTENSION(CopperKit))
@end


@interface RequestStack (SWIFT_EXTENSION(CopperKit))
- (void)set:(RequestStack * _Nonnull)stack;
@end


SWIFT_CLASS("_TtC9CopperKit18TouchAndHoldButton")
@interface TouchAndHoldButton : UIButton
- (void)addTarget:(id _Nonnull)target action:(SEL _Null_unspecified)action timeInterval:(NSTimeInterval)timeInterval;
- (void)sourceTouchUp:(UIButton * _Nonnull)sender;
- (void)sourceTouchDown:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIButton (SWIFT_EXTENSION(CopperKit))
@end


@interface UIColor (SWIFT_EXTENSION(CopperKit))
+ (UIColor * _Nonnull)copper_IdentitySheetBackgroundColor;
+ (UIColor * _Nonnull)copper_IdentitySheetNameColor;
+ (UIColor * _Nonnull)copper_IdentitySheetScopeColor;
+ (UIColor * _Nonnull)copper_IdentitySheetValueColor;
+ (UIColor * _Nonnull)copper_IdentitySheetTintColor;
+ (UIColor * _Nonnull)copper_IdentitySheetEditTextColor;
+ (UIColor * _Nonnull)copper_IdentitySheetTextInputPlaceholderTextColor;
+ (UIColor * _Nonnull)copper_IdentitySheetBorderColor;
+ (UIColor * _Nonnull)copper_IdentitySheetEditAvatarIconColor;
+ (UIColor * _Nonnull)copper_IdentitySheetSwitchColor;
+ (UIColor * _Nonnull)copper_IdentitySheetToggleValueLabelEnabledColor;
+ (UIColor * _Nonnull)copper_IdentitySheetToggleValueLabelDisabledColor;
+ (UIColor * _Nonnull)copper_IdentitySheetSwitchBackgroundColor;
+ (UIColor * _Nonnull)copper_IdentitySheetAvatarShadowColor;
+ (UIColor * _Nonnull)copper_IdentitySheetSettingsButtonColor;
+ (UIColor * _Nonnull)copper_DefaultAvatarIconColor;
+ (UIColor * _Nonnull)copper_IdentitySheetAvatarShadowViewBackgroundColor;
+ (UIColor * _Nonnull)copper_CardHeaderArrowColor;
+ (UIColor * _Nonnull)copper_CardHeaderTitleColor;
+ (UIColor * _Nonnull)copper_CardHeaderSubtitleColor;
+ (UIColor * _Nonnull)copper_ClientBackgroundColor;
+ (UIColor * _Nonnull)copper_ClientNameLabelColor;
+ (UIColor * _Nonnull)copper_ClientSecondaryLabelColor;
+ (UIColor * _Nonnull)copper_ApplicationCardIconBorderColor;
+ (UIColor * _Nonnull)copper_RequestSheetBackgroundColor;
+ (UIColor * _Nonnull)copper_RequestSheetBackgroundColorOverlay;
+ (UIColor * _Nonnull)copper_RequestSheetTableViewBackgroundColor;
+ (UIColor * _Nonnull)copper_RequestSheetBorderColor;
+ (UIColor * _Nonnull)copper_CopperRequestHeaderCloseButtonTintColor;
+ (UIColor * _Nonnull)copper_CopperRequestHeaderApplicationNameColor;
+ (UIColor * _Nonnull)copper_RequestSheetTableViewHeaderBackgroundColor;
+ (UIColor * _Nonnull)copper_RequestViewControllerQuickSelectDefaultColor;
+ (UIColor * _Nonnull)copper_RequestViewControllerQuickSelectSelectedColor;
+ (UIColor * _Nonnull)copper_RequestSheetHeaderTextColor;
+ (UIColor * _Nonnull)copper_RequestSheetValueColor;
+ (UIColor * _Nonnull)copper_RequestSheetTextInputPlaceholderTextColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenLabelColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenLabelDisabledColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonDismissedColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonSendingColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonSuccessColor;
+ (UIColor * _Nonnull)copper_RequestSheetOpenButtonSendingBorderColor;
+ (UIColor * _Nonnull)copper_RequestViewControllerOpenButtonGradientTop;
+ (UIColor * _Nonnull)copper_RequestViewControllerOpenButtonGradientBottom;
+ (UIColor * _Nonnull)copper_SettingsBackgroundColor;
+ (UIColor * _Nonnull)copper_SettingsSectionHeaderColor;
+ (UIColor * _Nonnull)copper_SettingsCellTitleTextColor;
+ (UIColor * _Nonnull)copper_SettingsCellSecondaryTextColor;
+ (UIColor * _Nonnull)copper_SettingsTableViewSeparatorColor;
+ (UIColor * _Nonnull)copper_SettingsSeparatorViewColor;
+ (UIColor * _Nonnull)copper_SettingsTableViewFooterVersionColor;
+ (UIColor * _Nonnull)copper_ContactsPickerTextColor;
+ (UIColor * _Nonnull)copper_ContactsPickerTintColor;
+ (UIColor * _Nonnull)copper_ContactsPickerViewBackgroundColor;
+ (UIColor * _Nonnull)copper_ContactsPickerPlaceholderTextColor;
+ (UIColor * _Nonnull)copper_ContactsPickerNavBarTintColor;
+ (UIColor * _Nonnull)copper_ContactsPickerHeaderBackgroundColor;
+ (UIColor * _Nonnull)copper_RegistrationViewBackgroundColor;
+ (UIColor * _Nonnull)copper_RegistrationViewPrimaryTextColor;
+ (UIColor * _Nonnull)copper_RegistrationViewSecondaryTextColor;
+ (UIColor * _Nonnull)copper_RegistrationViewErrorTextColor;
+ (UIColor * _Nonnull)copper_RegistrationViewBorderColor;
+ (UIColor * _Nonnull)copper_RegistrationViewSuccessColor;
+ (UIColor * _Nonnull)copper_RegistrationViewNumberPadHightlightColor;
+ (UIColor * _Nonnull)copper_IdentityCellKeyboardToolbarTintColor;
+ (UIColor * _Nonnull)copper_RegistrationColor;
+ (UIColor * _Nonnull)copper_ActivityIndicatorBackgroundColor;
+ (UIColor * _Nonnull)copper_AuthenticationControllerTitleColor;
+ (UIColor * _Nonnull)copper_AuthenticationControllerTextViewColor;
+ (UIColor * _Nonnull)copper_AuthenticationControllerButtonDefaultColor;
+ (UIColor * _Nonnull)copper_AuthenticationControllerButtonDisabledColor;
+ (UIColor * _Nonnull)copper_DocumentViewControllerPrimaryColor;
+ (UIColor * _Nonnull)copper_DocumentViewControllerTintColor;
+ (UIColor * _Nonnull)copper_primaryCopper;
+ (UIColor * _Nonnull)copper_primaryGreen;
+ (UIColor * _Nonnull)copper_primaryVerdigris;
+ (UIColor * _Nonnull)copper_midnightGrey;
+ (UIColor * _Nonnull)copper_secondaryBlue;
+ (UIColor * _Nonnull)copper_secondaryPurple;
+ (UIColor * _Nonnull)copper_secondaryPink;
+ (UIColor * _Nonnull)copper_secondaryRed;
+ (UIColor * _Nonnull)copper_secondaryOrange;
+ (UIColor * _Nonnull)copper_secondaryYellow;
+ (UIColor * _Nonnull)copper_softGreen;
+ (UIColor * _Nonnull)copper_softBlue;
+ (UIColor * _Nonnull)copper_softPurple;
+ (UIColor * _Nonnull)copper_softPink;
+ (UIColor * _Nonnull)copper_softOrange;
+ (UIColor * _Nonnull)copper_softYellow;
+ (UIColor * _Nonnull)copper_darkGreen;
+ (UIColor * _Nonnull)copper_darkBlue;
+ (UIColor * _Nonnull)copper_darkPurple;
+ (UIColor * _Nonnull)copper_darkBrown;
+ (UIColor * _Nonnull)copper_black;
+ (UIColor * _Nonnull)copper_black92;
+ (UIColor * _Nonnull)copper_black60;
+ (UIColor * _Nonnull)copper_black40;
+ (UIColor * _Nonnull)copper_black20;
+ (UIColor * _Nonnull)copper_black08;
+ (UIColor * _Nonnull)copper_white;
+ (UIColor * _Nonnull)copper_white95;
+ (UIColor * _Nonnull)copper_white72;
+ (UIColor * _Nonnull)copper_white52;
+ (UIColor * _Nonnull)copper_white32;
+ (UIColor * _Nonnull)copper_white20;
+ (UIColor * _Nonnull)hexStringToUIColor:(NSString * _Nonnull)hex;

/// Hex string of a UIColor instance.
///
/// \param rgba Whether the alpha should be included.
- (NSString * _Nonnull)hexString:(BOOL)includeAlpha;
@end


@interface UIFont (SWIFT_EXTENSION(CopperKit))
+ (UIFont * _Nonnull)copper_SectionHeaderFont;
+ (UIFont * _Nonnull)copper_PrimaryFont;
+ (UIFont * _Nonnull)copper_PrimaryItalicsFont;
+ (UIFont * _Nonnull)copper_SecondaryFont;
+ (UIFont * _Nonnull)copper_IdentitySheetNameFont;
+ (UIFont * _Nonnull)copper_IdentitySheetToggleValueLabelFont;
+ (UIFont * _Nonnull)copper_ClientIconFont;
+ (UIFont * _Nonnull)copper_RequestSheetHeaderNameFont;
+ (UIFont * _Nonnull)copper_RequestSheetOpenWithCopperFont;
+ (UIFont * _Nonnull)copper_CardHeaderTitleFont;
+ (UIFont * _Nonnull)copper_CardHeaderSubtitleFont;
+ (UIFont * _Nonnull)copper_SettingsTableViewFooterVersionFont;
+ (UIFont * _Nonnull)copper_CopperContactsPickerCellFont;
+ (UIFont * _Nonnull)copper_ContactsPickerNavigationBarFont;
+ (UIFont * _Nonnull)copper_ContactsPickerNavigationButtonFont;
+ (UIFont * _Nonnull)copper_RegistrationViewControlFont;
+ (UIFont * _Nonnull)copper_copper_RegistrationViewSuccessMessageFont;
+ (UIFont * _Nonnull)copper_RegistrationViewControlPlaceholderFont;
+ (UIFont * _Nonnull)copper_RegistrationViewControlLabelFont;
+ (UIFont * _Nonnull)copper_RegistrationViewNumberPadFont;
+ (UIFont * _Nonnull)copper_RegistrationViewNumberPadPressedFont;
@end

@class UIView;
@class UIImageView;

@interface UIImage (SWIFT_EXTENSION(CopperKit))
+ (UIImage * _Nonnull)toImage:(UIView * _Nonnull)view;
+ (UIImage * _Nonnull)crop:(UIImage * _Nonnull)image rect:(CGRect)rect;
+ (void)imageFromUrl:(NSString * _Nonnull)url callback:(void (^ _Nonnull)(UIImage * _Nullable))callback;
+ (CGSize)newSizeFromHeight:(UIImage * _Nonnull)image newHeight:(CGFloat)newHeight;
+ (UIImage * _Nonnull)imageWithImage:(UIImage * _Nonnull)image newSize:(CGSize)newSize;
- (UIImage * _Nonnull)roundImage;
+ (void)pulseImageView:(UIImageView * _Nonnull)imageView repeat:(BOOL)repeat;
@end

@class NSIndexPath;

@interface UITableView (SWIFT_EXTENSION(CopperKit))
- (UITableView * _Nullable)getTableView;
- (BOOL)isVisible:(NSIndexPath * _Nonnull)indexPath;
@property (nonatomic, readonly, strong) NSIndexPath * _Nonnull indexPathForLastCell;
@end


@interface UITextField (SWIFT_EXTENSION(CopperKit))
- (void)setPlaceholderColor:(UIColor * _Nonnull)color;
@end


@interface UITextView (SWIFT_EXTENSION(CopperKit))
- (void)boldSubstring:(NSString * _Nonnull)substr;
@end


@interface UIView (SWIFT_EXTENSION(CopperKit))
- (NSArray<UIView *> * _Nonnull)addBorderWithEdges:(UIRectEdge)edges color:(UIColor * _Nonnull)color thickness:(CGFloat)thickness;
- (void)shakeWithConstraint:(NSLayoutConstraint * _Nonnull)constraint withShakeDistance:(CGFloat)distance animationDuration:(double)animationDuration times:(NSInteger)times state:(NSInteger)state callback:(void (^ _Null_unspecified)(void))callback;
- (void)noticeWiggleWithConstant:(NSLayoutConstraint * _Nonnull)constraint withWiggleDistance:(CGFloat)withWiggleDistance animationDuration:(double)animationDuration completion:(void (^ _Null_unspecified)(void))completion;
@end

@class UserDevice;

SWIFT_CLASS("_TtC9CopperKit4User")
@interface User : NSObject <NSCoding>
+ (NSString * _Nonnull)CacheFile;
+ (void)setCacheFile:(NSString * _Nonnull)value;
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSArray<UserDevice *> * _Nonnull devices;
@property (nonatomic, strong) C29SecureSettings * _Null_unspecified secureSettings;
@property (nonatomic, strong) NSDate * _Nullable lastAuthenticationTimestamp;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (void)login:(BOOL)forceAuthTokenRefresh callback:(void (^ _Null_unspecified)(NSString * _Nullable, NSError * _Nullable))callback;
- (void)refreshUserApplications:(void (^ _Null_unspecified)(BOOL))callback;
- (void)refreshUserDevices:(NSString * _Nonnull)deviceId callback:(void (^ _Null_unspecified)(BOOL))callback;
- (void)isDeviceLoggedIn:(NSString * _Nonnull)deviceId callback:(void (^ _Nonnull)(BOOL))callback;
- (void)logoutOfUserDevice:(NSString * _Nonnull)deviceId callback:(void (^ _Nonnull)(BOOL))callback;
- (void)pollForLastRequest;
- (void)deleteUserFromAPI:(void (^ _Nonnull)(BOOL))callback;
- (void)resetUserData;
- (BOOL)load;
- (void)deleteFile;
- (void)save;
@end


@interface User (SWIFT_EXTENSION(CopperKit))
@end


@interface User (SWIFT_EXTENSION(CopperKit))
@end


@interface User (SWIFT_EXTENSION(CopperKit))
@end


SWIFT_CLASS("_TtC9CopperKit10UserDevice")
@interface UserDevice : NSObject <NSCoding>
@property (nonatomic, readonly, copy) NSString * _Null_unspecified deviceId;
@property (nonatomic, readonly, strong) NSDate * _Null_unspecified timestamp;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified name;
@property (nonatomic, readonly, strong) NSDate * _Null_unspecified lastActive;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified label;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (BOOL)isEqual:(id _Nullable)object;
@end


@interface UserDevice (SWIFT_EXTENSION(CopperKit))
@end

#pragma clang diagnostic pop
